server.port=${SERVER_PORT:8080}
spring.application.name=api-gateway

# ===============================
# ROUTES ? redirection vers chaque service
# ===============================

# Service Utilisateurs
spring.cloud.gateway.routes[0].id=service-utilisateurs
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/utilisateurs/**,/api/enseignants/**,/api/etudiants/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

# Service Soutenance
spring.cloud.gateway.routes[1].id=service-soutenance
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/soutenances/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

# Service Planification
spring.cloud.gateway.routes[2].id=service-planification
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/salles/**,/api/creneaux/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=0

# Service Jury
spring.cloud.gateway.routes[3].id=service-jury
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/jury/**,/api/notes/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=0

# Service Resultats
spring.cloud.gateway.routes[4].id=service-resultats
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/resultats/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=0

# ===============================
# JWT
# ===============================
JWT_SECRET=c291dGVuYW5jZV9zZWNyZXRfa2V5XzEyMzQ1Njc4OTAxMjM0NTY=
JWT_EXPIRATION=86400000

# ===============================
# LOGS
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.tn.microservices.apigateway=DEBUG
