spring.application.name=service-resultats
server.port=${SERVER_PORT:8085}

# --- H2 Local Database ---
spring.datasource.url=jdbc:h2:file:./data/resultats-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# --- RabbitMQ ---
spring.rabbitmq.addresses=amqps://rsfrdakb:iCRyAcshUHRxiw8hV0BsM8PyXZRajncU@chameleon.lmq.cloudamqp.com/rsfrdakb

logging.level.tn.microservices.serviceresultats=INFO
