spring.application.name=service-resultats
server.port=${SERVER_PORT:8085}

# --- PostgreSQL (Supabase) ---
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.vzxxczcdtqqksgmwqjnr
spring.datasource.password=gestionsoutenance2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# --- RabbitMQ ---
spring.rabbitmq.addresses=amqps://rsfrdakb:iCRyAcshUHRxiw8hV0BsM8PyXZRajncU@chameleon.lmq.cloudamqp.com/rsfrdakb


JWT_SECRET=8f3c9a2b7d91f4e6c0a5b8d7e9f1a2c3d4e5f6789a0b1c2d3e4f5a6b7c8d9e0
JWT_EXPIRATION=86400000
# Logging
logging.level.tn.microservices.serviceresultats=INFO
