spring.application.name=service-utilisateurs
server.port=8081

# --- H2 Local Database ---
spring.datasource.url=jdbc:h2:file:./data/utilisateurs-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# --- JWT ---
jwt.secret=c291dGVuYW5jZV9zZWNyZXRfa2V5XzEyMzQ1Njc4OTAxMjM0NTY=
jwt.expiration=86400000
