spring.application.name=service-utilisateurs
server.port=8081

# --- Connexion à Supabase (Cloud) ---
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.vzxxczcdtqqksgmwqjnr
spring.datasource.password=gestionsoutenance2026
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuration JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
